#ifndef CONFIG_H_
#define CONFIG_H_
#include "gefx_color.h"

#ifdef GEFX_WINDOW_WIDTH 
#define GEFX_GFX_WINDOW_STD_WIDTH GEFX_WINDOW_WIDTH 
#else 
#define GEFX_GFX_WINDOW_STD_WIDTH 800
#endif
#ifdef GEFX_WINDOW_HEIGHT
#define GEFX_GFX_WINDOW_STD_HEIGHT GEFX_WINDOW_HEIGHT
#else
#define GEFX_GFX_WINDOW_STD_HEIGHT 600
#endif
#ifdef GEFX_WINDOW_TITLE 
#define GEFX_GFX_WINDOW_STD_TITLE GEFX_WINDOW_TITLE
#else 
#define GEFX_GFX_WINDOW_STD_TITLE "GeFx"
#endif
#ifdef GEFX_WINDOW_BG
#define GEFX_GFX_WINDOW_STD_BG GEFX_WINDOW_BG
#else 
#define GEFX_GFX_WINDOW_STD_BG 0.2f, 0.3f, 0.3f, 1.0f
#endif
#ifdef GEFX_WINDOW_X
#define GEFX_GFX_WINDOW_STD_X GEFX_WINDOW_X
#else 
#define GEFX_GFX_WINDOW_STD_X 200.0f
#endif
#ifdef GEFX_WINDOW_Y
#define GEFX_GFX_WINDOW_STD_Y GEFX_WINDOW_Y
#else 
#define GEFX_GFX_WINDOW_STD_Y 200.0f
#endif
#ifdef GEFX_DRAWMODE
#define GEFX_GFX_RENDERER_STD_DRAWMODE GEFX_DRAWMODE
#else 
#define GEFX_GFX_RENDERER_STD_DRAWMODE GL_DYNAMIC_DRAW
#endif
#ifdef GEFX_RENDERER_DELAY
#define GEFX_GFX_RENDERER_STD_DELAY GEFX_RENDERER_DELAY
#else 
#define GEFX_GFX_RENDERER_STD_DELAY 0.016f
#endif
#ifdef GEFX_RESIZE_DELAY
#define GEFX_GFX_WINDOW_STD_RESIZE_DELAY GEFX_RESIZE_DELAY
#else 
#define GEFX_GFX_WINDOW_STD_RESIZE_DELAY 0.25f
#endif
#ifdef GEFX_OBJ_COLOR
#define GEFX_GFX_RENDERER_STD_OBJ_COLOR GEFX_OBJ_COLOR
#else 
#define GEFX_GFX_RENDERER_STD_OBJ_COLOR Fx::LIGHT_STEEL_BLUE
#endif
#ifdef GEFX_OFFSET
#define GEFX_GFX_RENDERER_STD_OBJ_OFFSET GEFX_OFFSET
#else
#define GEFX_GFX_RENDERER_STD_OBJ_OFFSET {0.0f, 0.0f}
#endif
#ifdef GEFX_FINAL_SCALE
#define GEFX_GFX_RENDERER_STD_FINAL_OBJ_SCALE GEFX_FINAL_SCALE
#else
#define GEFX_GFX_RENDERER_STD_FINAL_OBJ_SCALE {1.0f,1.0f}
#endif
#ifdef GEFX_INITIAL_SCALE
#define GEFX_GFX_RENDERER_STD_INITIAL_OBJ_SCALE GEFX_INITIAL_SCALE
#else
#define GEFX_GFX_RENDERER_STD_INITIAL_OBJ_SCALE {1.0f,1.0f}
#endif
#ifdef GEFX_RAND_SCALAR 
#define CONFNUM_GEFX_RAND_MAGIC_SCALAR GEFX_RAND_SCALAR
#else
#define CONFNUM_GEFX_RAND_MAGIC_SCALAR 62615533.0
#endif
#ifdef GEFX_RAND_BIAS 
#define CONFNUM_GEFX_RAND_MAGIC_BIAS GEFX_RAND_BIAS 
#else
#define CONFNUM_GEFX_RAND_MAGIC_BIAS 29717971.0
#endif
#ifdef GEFX_RAND_WIDTH 
#define CONFNUM_GEFX_RAND_WIDTH GEFX_RAND_WIDTH
#else
#define CONFNUM_GEFX_RAND_WIDTH 10000
#endif


#endif